version: '3'
services:
  spring-app:
    container_name: spring-app
    image: ${DOCKER_IMAGE_URL}
    env_file:
      - .env
    ports:
      - "8080:8080"
  nginx:
    container_name: nginx
    image: "nginx:test"
    ports:
      - "80:80"
    depends_on:
      - spring-app