spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/modak-user
#    username: MODAK_ADMIN
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:mysql://13.125.121.197:3306/modak
    username: modak-user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

    show_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
