spring:
  datasource:
    url: jdbc:mysql://test-mysql-3.chncbt2crztm.ap-northeast-2.rds.amazonaws.com:3306/modak2?tinyInt1isBit=false
    username: admin
    password: rladmswhd1

  jpa:
    hibernate:
      ddl-auto: create
    show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
