spring:

#  datasource:
#    url: jdbc:mysql://localhost:3306/modak?tinyInt1isBit=false
#    username: MODAK_ADMIN
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show_sql: true
#
  datasource:
    url: jdbc:mysql://15.164.86.236:3306/modak?tinyInt1isBit=false
    username: modak-user
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
